apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx-config : |
    server {
        listen 5000;
        location / {
            proxy_pass http://localhost:5000;
            proxy_set_header Host example.org;
            proxy_redirect "~^http[s]?:\/\/example.org\/(.*)$" $scheme://$http_host/$1;
        }
    }