apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-proxy
  name: example-proxy
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: example-proxy
  sessionAffinity: None
  type: ClusterIP