apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvclaim1
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      name: persistent-volume